services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head && uvicorn app.asgi:app --host 0.0.0.0 --port 8000"

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_started
    volumes:
      - .:/app

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
